In [ ]:
!pip install langchain_community

Collecting langchain_community
  Downloading langchain_community-0.4.2-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (3.14.1)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (0.4.3)
Collecting langchain-classic<2.0.0,>=1.0.7 (from langchain_community)
  Downloading langchain_classic-1.0.8-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (1.4.3)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (0.8.12)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (2.0.2)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (2.14.1)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (6.0.3)
Collecting requests<3.0.0,>=2.32.5 (from langchain_community)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (2.0.50)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (9.1.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (0.5.2)
Requirement already satisfied: typing_extensions>=4.4 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (4.15.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.24.2)
Collecting langchain-core<2.0.0,>=1.4.0 (from langchain_community)
  Downloading langchain_core-1.4.8-py3-none-any.whl.metadata (4.7 kB)
Collecting langchain-text-splitters<2.0.0,>=1.1.2 (from langchain-classic<2.0.0,>=1.0.7->langchain_community)
  Downloading langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.7->langchain_community) (2.12.3)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain_community) (1.33)
Collecting langchain-protocol>=0.0.17 (from langchain-core<2.0.0,>=1.4.0->langchain_community)
  Downloading langchain_protocol-0.0.18-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain_community) (26.2)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain_community) (0.16.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (1.0.0)
Requirement already satisfied: websockets>=15.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (15.0.1)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (3.7.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (0.25.0)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain_community) (1.2.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain_community) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain_community) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain_community) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain_community) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain_community) (2026.5.20)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain_community) (3.5.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.0->langchain_community) (3.1.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain_community) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain_community) (2.41.4)
Downloading langchain_community-0.4.2-py3-none-any.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 28.6 MB/s eta 0:00:00
Downloading langchain_classic-1.0.8-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 46.4 MB/s eta 0:00:00
Downloading langchain_core-1.4.8-py3-none-any.whl (557 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.4/557.4 kB 29.5 MB/s eta 0:00:00
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 4.9 MB/s eta 0:00:00
Downloading langchain_protocol-0.0.18-py3-none-any.whl (7.2 kB)
Downloading langchain_text_splitters-1.1.2-py3-none-any.whl (35 kB)
Installing collected packages: requests, langchain-protocol, langchain-core, langchain-text-splitters, langchain-classic, langchain_community
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
  Attempting uninstall: langchain-protocol
    Found existing installation: langchain-protocol 0.0.16
    Uninstalling langchain-protocol-0.0.16:
      Successfully uninstalled langchain-protocol-0.0.16
  Attempting uninstall: langchain-core
    Found existing installation: langchain-core 1.4.3
    Uninstalling langchain-core-1.4.3:
      Successfully uninstalled langchain-core-1.4.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
Successfully installed langchain-classic-1.0.8 langchain-core-1.4.8 langchain-protocol-0.0.18 langchain-text-splitters-1.1.2 langchain_community-0.4.2 requests-2.34.2

In [2]:
!pip install langchain_chroma

Collecting langchain_chroma
  Downloading langchain_chroma-1.1.0-py3-none-any.whl.metadata (1.9 kB)
Collecting chromadb<2.0.0,>=1.3.5 (from langchain_chroma)
  Downloading chromadb-1.5.9-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.0 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from langchain_chroma) (1.4.8)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from langchain_chroma) (2.0.2)
Collecting build>=1.0.3 (from chromadb<2.0.0,>=1.3.5->langchain_chroma)
  Downloading build-1.5.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.12.3)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.14.1)
Collecting pybase64>=1.4.1 (from chromadb<2.0.0,>=1.3.5->langchain_chroma)
  Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (8.7 kB)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.49.0)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (4.15.0)
Collecting onnxruntime>=1.14.1 (from chromadb<2.0.0,>=1.3.5->langchain_chroma)
  Downloading onnxruntime-1.27.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.4 kB)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.38.0)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb<2.0.0,>=1.3.5->langchain_chroma)
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.42.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.38.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.22.2)
Collecting pypika>=0.48.9 (from chromadb<2.0.0,>=1.3.5->langchain_chroma)
  Downloading pypika-0.51.1-py2.py3-none-any.whl.metadata (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 2.4 MB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (4.67.3)
Collecting overrides>=7.3.1 (from chromadb<2.0.0,>=1.3.5->langchain_chroma)
  Downloading overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (7.1.0)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.81.0)
Collecting bcrypt>=4.0.1 (from chromadb<2.0.0,>=1.3.5->langchain_chroma)
  Downloading bcrypt-5.0.0-cp39-abi3-manylinux_2_34_x86_64.whl.metadata (10 kB)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.25.1)
Collecting kubernetes>=28.1.0 (from chromadb<2.0.0,>=1.3.5->langchain_chroma)
  Downloading kubernetes-36.0.2-py2.py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (3.11.9)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (4.26.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.1.3->langchain_chroma) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.1.3->langchain_chroma) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.1.3->langchain_chroma) (0.8.12)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.1.3->langchain_chroma) (26.2)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.1.3->langchain_chroma) (0.16.0)
Collecting pyproject_hooks (from build>=1.0.3->chromadb<2.0.0,>=1.3.5->langchain_chroma)
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.1.3->langchain_chroma) (3.1.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2026.5.1)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.34.2)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.5.0)
Collecting durationpy>=0.7 (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma)
  Downloading durationpy-0.10-py3-none-any.whl.metadata (340 bytes)
Requirement already satisfied: aiohttp<4.0.0,>=3.13.5 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (3.14.1)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.1.3->langchain_chroma) (1.0.0)
Requirement already satisfied: websockets>=15.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.1.3->langchain_chroma) (15.0.1)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.1.3->langchain_chroma) (3.7.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.1.3->langchain_chroma) (0.25.0)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain_chroma) (25.12.19)
Requirement already satisfied: protobuf>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain_chroma) (5.29.6)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (8.7.1)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.75.0)
Collecting opentelemetry-exporter-otlp-proto-common==1.42.1 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma)
  Downloading opentelemetry_exporter_otlp_proto_common-1.42.1-py3-none-any.whl.metadata (1.8 kB)
Collecting opentelemetry-proto==1.42.1 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma)
  Downloading opentelemetry_proto-1.42.1-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb<2.0.0,>=1.3.5->langchain_chroma)
  Downloading opentelemetry_sdk-1.42.1-py3-none-any.whl.metadata (1.7 kB)
Collecting opentelemetry-api>=1.2.0 (from chromadb<2.0.0,>=1.3.5->langchain_chroma)
  Downloading opentelemetry_api-1.42.1-py3-none-any.whl.metadata (1.4 kB)
Collecting opentelemetry-semantic-conventions==0.63b1 (from opentelemetry-sdk>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma)
  Downloading opentelemetry_semantic_conventions-0.63b1-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.20.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.18.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (8.4.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.0.4)
Requirement already satisfied: httptools>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.8.0)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.2.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.24.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain_chroma) (3.29.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.5.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (3.4.7)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (3.3.1)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (4.1.0)
Downloading langchain_chroma-1.1.0-py3-none-any.whl (12 kB)
Downloading chromadb-1.5.9-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (23.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.3/23.3 MB 22.3 MB/s eta 0:00:00
Downloading bcrypt-5.0.0-cp39-abi3-manylinux_2_34_x86_64.whl (278 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 9.4 MB/s eta 0:00:00
Downloading build-1.5.0-py3-none-any.whl (26 kB)
Downloading kubernetes-36.0.2-py2.py3-none-any.whl (4.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 15.9 MB/s eta 0:00:00
Downloading onnxruntime-1.27.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.7/18.7 MB 31.0 MB/s eta 0:00:00
Downloading opentelemetry_exporter_otlp_proto_grpc-1.42.1-py3-none-any.whl (19 kB)
Downloading opentelemetry_exporter_otlp_proto_common-1.42.1-py3-none-any.whl (17 kB)
Downloading opentelemetry_proto-1.42.1-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.8/71.8 kB 3.8 MB/s eta 0:00:00
Downloading opentelemetry_sdk-1.42.1-py3-none-any.whl (170 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.9/170.9 kB 8.0 MB/s eta 0:00:00
Downloading opentelemetry_api-1.42.1-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 kB 3.5 MB/s eta 0:00:00
Downloading opentelemetry_semantic_conventions-0.63b1-py3-none-any.whl (203 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.7/203.7 kB 7.4 MB/s eta 0:00:00
Downloading overrides-7.7.0-py3-none-any.whl (17 kB)
Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 3.1 MB/s eta 0:00:00
Downloading pypika-0.51.1-py2.py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 3.1 MB/s eta 0:00:00
Downloading durationpy-0.10-py3-none-any.whl (3.9 kB)
Downloading pyproject_hooks-1.2.0-py3-none-any.whl (10 kB)
Installing collected packages: pypika, durationpy, pyproject_hooks, pybase64, overrides, opentelemetry-proto, opentelemetry-api, onnxruntime, bcrypt, opentelemetry-semantic-conventions, opentelemetry-exporter-otlp-proto-common, build, opentelemetry-sdk, kubernetes, opentelemetry-exporter-otlp-proto-grpc, chromadb, langchain_chroma
  Attempting uninstall: opentelemetry-proto
    Found existing installation: opentelemetry-proto 1.38.0
    Uninstalling opentelemetry-proto-1.38.0:
      Successfully uninstalled opentelemetry-proto-1.38.0
  Attempting uninstall: opentelemetry-api
    Found existing installation: opentelemetry-api 1.38.0
    Uninstalling opentelemetry-api-1.38.0:
      Successfully uninstalled opentelemetry-api-1.38.0
  Attempting uninstall: opentelemetry-semantic-conventions
    Found existing installation: opentelemetry-semantic-conventions 0.59b0
    Uninstalling opentelemetry-semantic-conventions-0.59b0:
      Successfully uninstalled opentelemetry-semantic-conventions-0.59b0
  Attempting uninstall: opentelemetry-exporter-otlp-proto-common
    Found existing installation: opentelemetry-exporter-otlp-proto-common 1.38.0
    Uninstalling opentelemetry-exporter-otlp-proto-common-1.38.0:
      Successfully uninstalled opentelemetry-exporter-otlp-proto-common-1.38.0
  Attempting uninstall: opentelemetry-sdk
    Found existing installation: opentelemetry-sdk 1.38.0
    Uninstalling opentelemetry-sdk-1.38.0:
      Successfully uninstalled opentelemetry-sdk-1.38.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 1.29.0 requires opentelemetry-api<1.39.0,>=1.36.0, but you have opentelemetry-api 1.42.1 which is incompatible.
google-adk 1.29.0 requires opentelemetry-sdk<1.39.0,>=1.36.0, but you have opentelemetry-sdk 1.42.1 which is incompatible.
opentelemetry-exporter-gcp-logging 1.11.0a0 requires opentelemetry-sdk<1.39.0,>=1.35.0, but you have opentelemetry-sdk 1.42.1 which is incompatible.

In [ ]:
!pip install langchain_google_genai

Collecting langchain_google_genai
  Downloading langchain_google_genai-4.2.5-py3-none-any.whl.metadata (2.7 kB)
Collecting filetype<2.0.0,>=1.2.0 (from langchain_google_genai)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: google-genai<3.0.0,>=1.65.0 in /usr/local/lib/python3.12/dist-packages (from langchain_google_genai) (1.68.0)
Requirement already satisfied: langchain-core<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from langchain_google_genai) (1.4.8)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain_google_genai) (2.12.3)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<3.0.0,>=1.65.0->langchain_google_genai) (4.13.0)
Requirement already satisfied: google-auth<3.0.0,>=2.47.0 in /usr/local/lib/python3.12/dist-packages (from google-auth[requests]<3.0.0,>=2.47.0->google-genai<3.0.0,>=1.65.0->langchain_google_genai) (2.47.0)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai<3.0.0,>=1.65.0->langchain_google_genai) (0.28.1)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai<3.0.0,>=1.65.0->langchain_google_genai) (2.34.2)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from google-genai<3.0.0,>=1.65.0->langchain_google_genai) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<3.0.0,>=1.65.0->langchain_google_genai) (15.0.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<3.0.0,>=1.65.0->langchain_google_genai) (4.15.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<3.0.0,>=1.65.0->langchain_google_genai) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from google-genai<3.0.0,>=1.65.0->langchain_google_genai) (1.3.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.3.2->langchain_google_genai) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.3.2->langchain_google_genai) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.3.2->langchain_google_genai) (0.8.12)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.3.2->langchain_google_genai) (26.2)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.3.2->langchain_google_genai) (6.0.3)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.3.2->langchain_google_genai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->langchain_google_genai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->langchain_google_genai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->langchain_google_genai) (0.4.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0.0,>=4.8.0->google-genai<3.0.0,>=1.65.0->langchain_google_genai) (3.18)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<3.0.0,>=1.65.0->langchain_google_genai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<3.0.0,>=1.65.0->langchain_google_genai) (4.9.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai<3.0.0,>=1.65.0->langchain_google_genai) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai<3.0.0,>=1.65.0->langchain_google_genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai<3.0.0,>=1.65.0->langchain_google_genai) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.3.2->langchain_google_genai) (3.1.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.3.2->langchain_google_genai) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.3.2->langchain_google_genai) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.3.2->langchain_google_genai) (3.7.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.3.2->langchain_google_genai) (0.25.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->google-genai<3.0.0,>=1.65.0->langchain_google_genai) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->google-genai<3.0.0,>=1.65.0->langchain_google_genai) (2.5.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<3.0.0,>=1.65.0->langchain_google_genai) (0.6.3)
Downloading langchain_google_genai-4.2.5-py3-none-any.whl (69 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 kB 2.4 MB/s eta 0:00:00
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Installing collected packages: filetype, langchain_google_genai
Successfully installed filetype-1.2.0 langchain_google_genai-4.2.5

In [4]:
!pip install langchain_huggingface

Collecting langchain_huggingface
  Downloading langchain_huggingface-1.2.2-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: huggingface-hub<2.0.0,>=0.33.4 in /usr/local/lib/python3.12/dist-packages (from langchain_huggingface) (1.18.0)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.31 in /usr/local/lib/python3.12/dist-packages (from langchain_huggingface) (1.4.8)
Requirement already satisfied: tokenizers<1.0.0,>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from langchain_huggingface) (0.22.2)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (3.29.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (4.67.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (4.15.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (0.8.12)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (2.12.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (9.1.4)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (0.16.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (3.1.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (2.34.2)
Requirement already satisfied: websockets>=15.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (15.0.1)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (3.7.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (0.4.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (0.0.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (0.1.2)
Downloading langchain_huggingface-1.2.2-py3-none-any.whl (31 kB)
Installing collected packages: langchain_huggingface
Successfully installed langchain_huggingface-1.2.2

In [5]:
import json
import numpy as np
import pandas as pd

import os
from IPython.display import display, HTML
import markdown

from langchain_community.document_loaders import DirectoryLoader, TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

/tmp/ipykernel_5157/2649713805.py:9: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import DirectoryLoader, TextLoader

In [10]:
courses = pd.read_json("/content/kayfa_courses.json")
# courses.head(3)

In [12]:
roadmaps = pd.read_json("/content/kayfa_roadmaps.json")
# roadmaps.head(2)

In [14]:
path = "/content/text files"
documents = []
labels = []

files = os.listdir(path)
for file in files:
    with open(f"{path}/{file}", 'r', encoding='utf-8') as f:
        content = f.read().strip()
        documents.append(content)
        labels.append(file.split(".")[0].replace('_',' ').title())

In [15]:
labels

['Kayfa Privacy Policy',
 'Kayfa Company Overview',
 'Kayfa Instructor Network',
 'Kayfa Soc Diploma',
 'Kayfa Paid Individual Courses',
 'Kayfa Ai Diploma',
 'Kayfa Fullstack Diploma',
 'Kayfa Data Science Diploma',
 'Kayfa Free Educational Content',
 'Kayfa Policies And Faqs',
 'Kayfa Pentest Diploma',
 'Kayfa Paid Educational Tracks']

In [16]:
path = "/content/text files"
loader = DirectoryLoader(
    path,
    glob="**/*.md",
    loader_cls=TextLoader,
    loader_kwargs={'encoding': 'utf-8'}
)
documents = loader.load()

In [17]:
documents[0]

Document(metadata={'source': '/content/text files/kayfa_privacy_policy.md'}, page_content='# Kayfa Privacy Policy\n\nThis document summarizes the key aspects of Kayfa\'s Privacy Policy, focusing on data collection, usage, and user rights, optimized for AI agent retrieval.\n\n## Data Controller and Purpose\n\nKayfa is the **data controller**, responsible for deciding how personal information is collected, stored, and used [1]. The purpose of data collection is to provide services, communicate with users, troubleshoot issues, secure against fraud, improve services, analyze usage, serve personalized advertising, and comply with legal requirements [1].\n\n## Information Collected\n\nThe following personal data is collected upon account registration and use of services [1]:\n\n*   **Identity and Contact:** Name, Email Address, Year of Birth, Gender, Country of Residence/Origin, Phone Numbers, Social Media Accounts (if used for login).\n*   **Usage Data:** Records of visits to Kayfa and engagement with educational content (pages, videos, assessments, posts, comments, and other interactions).\n*   **Technical Data:** Information collected through automated means like cookies and web beacons to enable site functionality, remember preferences, and secure the site [1].\n\n## User Rights\n\nUsers have several rights regarding their personal data [1]:\n\n*   **Right to Access:** Request access to personal data held and information about its processing.\n*   **Right to Rectification:** Request correction or update of inaccurate or incomplete information.\n*   **Right to Erasure:** Request deletion of personal data in certain circumstances.\n*   **Right to Restrict Processing:** Request restriction of processing under certain conditions.\n*   **Right to Object:** Object to the processing of personal data (e.g., for direct marketing).\n\nTo exercise these rights, users should contact Kayfa at **info@kayfa.io** [1].\n\n## Source\n\n[1] https://kayfa.io/privacy/ "Privacy Policy | Kayfa Platform"\n')

In [18]:
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=100)
chunks = text_splitter.split_documents(documents)

In [19]:
embeddings_model = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [20]:
persist_dir = "/content/MyVectorDB"
vector_database = Chroma.from_documents(
    documents=chunks,
    embedding=embeddings_model,
    persist_directory=persist_dir
)

In [21]:
!zip -r MyVectorDB.zip /content/MyVectorDB

  adding: content/MyVectorDB/ (stored 0%)
  adding: content/MyVectorDB/chroma.sqlite3 (deflated 69%)
  adding: content/MyVectorDB/2f9701a1-1a27-40e9-b627-840f529e646c/ (stored 0%)
  adding: content/MyVectorDB/2f9701a1-1a27-40e9-b627-840f529e646c/length.bin (deflated 68%)
  adding: content/MyVectorDB/2f9701a1-1a27-40e9-b627-840f529e646c/header.bin (deflated 63%)
  adding: content/MyVectorDB/2f9701a1-1a27-40e9-b627-840f529e646c/data_level0.bin (deflated 100%)
  adding: content/MyVectorDB/2f9701a1-1a27-40e9-b627-840f529e646c/link_lists.bin (stored 0%)

In [22]:
from google.colab import files
files.download('MyVectorDB.zip')

In [23]:
retriever = vector_database.as_retriever(search_type="similarity", search_kwargs={'k': 3})

In [24]:
retriever.invoke("what is your best thing about data science course")

[Document(id='3b078896-ce06-4ae3-a7e5-bc63305e8b99', metadata={'source': '/content/text files/kayfa_data_science_diploma.md'}, page_content='# 📊 Product: Data Science Track by Kayfa\n**Pitch:** A rigorous 5-month hybrid program designed to transform beginners into professional Data Scientists through a blend of flexible learning and live, interactive mentorship.\n\n## 🛠️ The Technical Stack (Curriculum Highlights)\n* **Data Mastery with Python:** Deep dive into cleaning, scraping, and analysis using Pandas, NumPy, and OOP concepts.\n* **Business Intelligence & SQL:** Build professional dashboards with **Power BI** and manage enterprise data using **MS SQL Server** (queries, stored procedures).\n* **Advanced Analytics:** Go beyond basics with **Advanced Excel** (Pivot Tables, DAX, Power Query) and Business Statistics.\n* **Machine Learning:** Build predictive models using Supervised/Unsupervised learning, Neural Networks, and Regression algorithms.\n* **Applied Experience:** Students solve real business problems through 2 major Capstone Projects and continuous hands-on workshops.'),
 Document(id='dfc6170f-75d1-461f-9d27-73e73dbda46d', metadata={'source': '/content/text files/kayfa_free_educational_content.md'}, page_content='| Course Name | Videos | Hours | Instructor/Focus |\n| :--- | :--- | :--- | :--- |\n| **SOC Tips** | 35 | 1:18 | Security Operations Center (SOC) |\n| **Programming Tips** | 30 | 1:0 | Programming |\n| **AI Tips** | 5 | 0:5 | Artificial Intelligence |\n| **Data Science Tips** | 4 | 0:3 | Data Science |\n| **General Courses Tips** | 4 | 0:4 | General Topics |\n| **Free Sessions** | 45 | 12:5 | Various Topics |\n| **Introduction to Data Science** | 1 | 0:10 | Osama Salem (CEO of Etica Technology) |\n| **Live Session - All About Data Science** | 9 | 3:19 | Osama Salem |\n| **HTML Tips** | 8 | 0:8 | Mohamed Ali (Full-Stack Web Developer) |\n| **QRadar Professional Pathway TIPS** | 6 | 0:19 | Hatem Metwally (Information Security Consultant) |\n| **Network and Security Fundamentals Tips** | 7 | 0:8 | Ahmed Shalaby (Senior Cyber Security Engineer) |\n\n## Source\n\n[1] https://kayfa.io/search/ "Search | Kayfa Platform"'),
 Document(id='55a1cdca-58ed-4331-a99b-a936ca092cf1', metadata={'source': '/content/text files/kayfa_paid_individual_courses.md'}, page_content='| Course Name | Videos | Hours | Price (USD) | Instructor/Focus |\n| :--- | :--- | :--- | :--- | :--- |\n| **Business Statistics** | 137 | 12:38 | 65 | Prof. Mostafa Elhosseini |\n| **MS SQL Server Programming** | 87 | 10:3 | 35 | Hagar Ibrahiem |\n| **Data Visualization by Power Bi** | 79 | 6:13 | 30 | Eman Raslan |\n| **Network and Security Fundamentals** | 94 | 4:48 | 30 | Ahmed Shalaby |\n| **HTML** | 42 | 5:12 | 30 | Mohamed Ali |\n| **Fundamentals of Graphic Design** | 46 | 2:35 | 30 | Heba Hashem Abdeen |\n| **Microsoft Windows Active Directory** | 74 | 6:21 | 35 | Abdelbaky Shehata |\n| **Linux Fundamentals** | 32 | 5:19 | 40 | Yehia kandeel |\n| **Splunk SIEM Case Studies** | 19 | 2:36 | 50 | Motasem Hamdan |\n| **How AI & Chat GPT Work** | 29 | 2:1 | 20 | Mohammad Thabet |\n| **Introduction to JavaScript** | 22 | 2:35 | 20 | Mohamed Ali |\n| **Introduction to TypeScript** | 28 | 2:33 | 20 | Ahmed Saber |\n| **Introduction to Marketing** | 12 | 0:57 | 15 | Walid Saed |')]

In [25]:
from getpass import getpass
API = getpass("Google API Key: ")

Google API Key: ··········

In [50]:
# llm = ChatGoogleGenerativeAI(
#     model="gemini-1.5-flash",
#     google_api_key=API,
#     temperature=0
# )

In [26]:
courses.head(1)

,id,provider,host,name,track,summary,link,duration,level,prerequisites,roadmaps
0,kayfa_business_statistics,kayfa,kayfa,Business Statistics,"[data_science, data_analysis]",A comprehensive course covering business stati...,https://kayfa.io/courses/business-statistics-f...,12 hours 38 minutes,intermediate,Basic math knowledge,"[kayfa_data_science_track, kayfa_data_analysis..."

In [30]:
courses.describe()

,id,provider,host,name,track,summary,link,duration,level,prerequisites,roadmaps
count,48,48,48,48,48,48,48,48,48,20,39
unique,48,1,1,48,22,48,48,32,3,18,11
top,kayfa_business_statistics,kayfa,kayfa,Business Statistics,"[cybersecurity, soc]",A comprehensive course covering business stati...,https://kayfa.io/courses/business-statistics-f...,5 hours,beginner,SOC Fundamentals,[kayfa_data_science_track]
freq,1,48,48,1,8,1,1,6,31,2,9

In [31]:
courses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             48 non-null     object
 1   provider       48 non-null     object
 2   host           48 non-null     object
 3   name           48 non-null     object
 4   track          48 non-null     object
 5   summary        48 non-null     object
 6   link           48 non-null     object
 7   duration       48 non-null     object
 8   level          48 non-null     object
 9   prerequisites  20 non-null     object
 10  roadmaps       39 non-null     object
dtypes: object(11)
memory usage: 4.3+ KB

In [32]:
roadmaps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             13 non-null     object
 1   name           13 non-null     object
 2   summary        13 non-null     object
 3   provider       13 non-null     object
 4   host           13 non-null     object
 5   track          13 non-null     object
 6   skills         13 non-null     object
 7   tools          13 non-null     object
 8   duration       13 non-null     object
 9   courses_count  13 non-null     int64
 10  link           13 non-null     object
 11  courses_list   13 non-null     object
dtypes: int64(1), object(11)
memory usage: 1.3+ KB

In [ ]:
import pandas as pd
from langchain_core.tools import tool
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.prebuilt import create_react_agent

embeddings_model = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
vector_database = Chroma(
    persist_directory="/content/MyVectorDB",
    embedding_function=embeddings_model
)
retriever = vector_database.as_retriever(search_type="similarity", search_kwargs={'k': 4})

@tool
def search_courses_db(name: str, track: str = None, max_price: float = None, level: str = None) -> str:
    """
    Use this tool for a detailed search of the course database (course names, prices, duration, level).
    Do not use it to search for policies or general details.
    """
    filtered_df = courses.copy()

    # if max_price:
    #     filtered_df = filtered_df[filtered_df['price'] <= max_price]
    if name:
        filtered_df = filtered_df[filtered_df['name'].str.contains(name, case=False, na=False)]
    if track:
        filtered_df = filtered_df[filtered_df['track'].str.contains(track, case=False, na=False)]
    if level:
        filtered_df = filtered_df[filtered_df['level'].str.contains(level, case=False, na=False)]
    if filtered_df.empty:
        return "can't find any courses with these search filters."
    return filtered_df.to_json(orient='records', force_ascii=False)

@tool
def search_roadmaps_db(name: str, track: str = None, skills:str = None) -> str:
    """Use this tool to find out details of the Roadmaps, the number of courses within the roadmap, and the tools used in it."""
    filtered_df = roadmaps.copy()
    if name:
        filtered_df = filtered_df[filtered_df['name'].str.contains(name, case=False, na=False)]
    if track:
        filtered_df = filtered_df[filtered_df['track'].str.contains(track, case=False, na=False)]
    if skills:
        filtered_df = filtered_df[filtered_df['skills'].str.contains(skills, case=False, na=False)]
    if filtered_df.empty:
        return "can't find any roadmaps with these search filters."
    return filtered_df.to_json(orient='records', force_ascii=False)

@tool
def query_knowledge_base(question: str) -> str:
    """
    Use this tool to search the academy's files knowledge base for:
    - Refund policies and frequently asked questions (FAQs).
    - Details about specific diplomas (SOC, AI, Fullstack, Data Science, Pentest) and how to apply.
    - Free and paid content.
    - Information about the company and instructors.
    """
    docs = retriever.invoke(question)

    if not docs:
        return "No informations found at the knowledge base"

    formatted_context = "\n\n".join(
        f"source: {doc.metadata.get('label', 'unknown')}\ninformations: {doc.page_content}"
        for doc in docs
    )
    return f"founded informations:\n{formatted_context}"

# Name, phone / WhatsApp, email, city or country, preferred language & dialect, and best contact channel and time.
@tool
def capture_crm_lead(name: str, phone: str, email:str = None, country: str =None, language:str=None, interest: str =None, conversation_summary: str = None, state: str =None) -> str:
    """
    Use this tool only when the customer shows a clear intent to purchase or requests registration.
    The tool saves customer data to the MongoDB database.
    """

    ticket = {
        "Name": name,
        "Phone Number": phone,
        "Email": email,
        "Country": country,
        "Interest": interest,
        "Conversational Summary": conversation_summary
    }

    db = get_db_connection(uri)
    collection = db["tickets"]

    current_year = datetime.datetime.now().year
    random_id = random.randint(1000, 9999)
    ticket_id = f"LEAD-{current_year}-{random_id}"


    result = collection.insert_one(ticket)

    print(f"New Ticket have been recorded: {ticket}\n")
    return "Customer data have been saved successfully!"

llm = ChatGoogleGenerativeAI(model="gemini-3.1-flash-lite-preview", google_api_key=API, temperature=0.1)

tools = [search_courses_db, search_roadmaps_db, query_knowledge_base, capture_crm_lead]

system_prompt = """
You are a professional sales assistant for Kayfa Academy.
Your tasks:
1. Understand the client's needs and answer accurately using the available tools.
2. Do not invent any information (prices, durations, policies). If you are unsure, use the 'query_knowledge_base' tool.
3. For questions about a specific diploma (such as SOC or Data Science), use the 'query_knowledge_base' to gather marketing and persuasive details.
4. To search for prices and courses, use 'search_courses_db' or 'search_roadmaps_db'.
5. Start with individual/free courses for hesitant clients, and direct serious clients to diplomas.
6. If the client expresses interest in registering, ask for their name and number, then use the 'capture_crm_lead' tool to silently save the data, and then inform them that the process is complete.
7. Speak in natural and friendly Arabic.
"""

sales_agent = create_react_agent(llm, tools)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

/tmp/ipykernel_5157/4234178313.py:103: LangGraphDeprecatedSinceV10: create_react_agent has been moved to `langchain.agents`. Please update your import to `from langchain.agents import create_agent`. Deprecated in LangGraph V1.0 to be removed in V2.0.
  sales_agent = create_react_agent(llm, tools)

In [60]:
messages = {
        "messages": [
            ("system", system_prompt),
        ]
    }

def add_message(sender,message):
    if sender=='ai':
        messages['messages'].append(('ai',message))
    elif sender=='human':
        messages['messages'].append(('human',message))
    else:
        return f"Value Error '{sender}': Sender must be either 'ai' or 'human' not {sender}!"

In [61]:
messages

{'messages': [('system',
   "\nYou are a professional sales assistant for Kayfa Academy.\nYour tasks:\n1. Understand the client's needs and answer accurately using the available tools.\n2. Do not invent any information (prices, durations, policies). If you are unsure, use the 'query_knowledge_base' tool.\n3. For questions about a specific diploma (such as SOC or Data Science), use the 'query_knowledge_base' to gather marketing and persuasive details.\n4. To search for prices and courses, use 'search_courses_db' or 'search_roadmaps_db'.\n5. Start with individual/free courses for hesitant clients, and direct serious clients to diplomas.\n6. If the client expresses interest in registering, ask for their name and number, then use the 'capture_crm_lead' tool to silently save the data, and then inform them that the process is complete.\n7. Speak in natural and friendly Arabic.\n")]}

In [74]:
def chat():
  for m in messages['messages']:
    if m[0]=='human':
      print(f"Human: {m[1]}")
    elif m[0]=='ai':
      print(f"AI: {m[1]}")
  message = ''
  while message!='close':
    print("\n\n")
    message = input("You: ")
    add_message('human', message)
    print(message)
    response = sales_agent.invoke(messages)
    print(response['messages'][-1].content[0]['text'])
    add_message('ai', response['messages'][-1].content[0]['text'])

### Testing Agent

In [64]:
add_message('human', 'اهلا بفكر اقدم في كورس جديد ترشحلي ايه')

In [65]:
response = sales_agent.invoke(messages)

In [66]:
print(response['messages'][-1].content[0]['text'])

أهلاً بك! يسعدني جداً اهتمامك بتطوير مهاراتك مع أكاديمية "كيفا".

عشان أقدر أرشحلك الكورس الأنسب ليك، محتاج أعرف منك شوية تفاصيل بسيطة:
1. إيه هو المجال اللي بتميل ليه أو حابب تتعلمه؟ (مثلاً: البرمجة، الأمن السيبراني، تحليل البيانات، أو غيرهم).
2. إيه هو مستواك الحالي في المجال ده؟ (مبتدئ، متوسط، أو محترف).
3. هل بتدور على كورس قصير ومحدد لمهارة معينة، ولا بتفكر في "دبلومة" متكاملة تأهلك لسوق العمل؟

بانتظار ردك عشان أقدر أساعدك تختار المسار الصح!

In [67]:
messages

{'messages': [('system',
   "\nYou are a professional sales assistant for Kayfa Academy.\nYour tasks:\n1. Understand the client's needs and answer accurately using the available tools.\n2. Do not invent any information (prices, durations, policies). If you are unsure, use the 'query_knowledge_base' tool.\n3. For questions about a specific diploma (such as SOC or Data Science), use the 'query_knowledge_base' to gather marketing and persuasive details.\n4. To search for prices and courses, use 'search_courses_db' or 'search_roadmaps_db'.\n5. Start with individual/free courses for hesitant clients, and direct serious clients to diplomas.\n6. If the client expresses interest in registering, ask for their name and number, then use the 'capture_crm_lead' tool to silently save the data, and then inform them that the process is complete.\n7. Speak in natural and friendly Arabic.\n"),
  ('human', 'اهلا بفكر اقدم في كورس جديد ترشحلي ايه')]}

In [75]:
chat()

Human: اهلا بفكر اقدم في كورس جديد ترشحلي ايه
Human: اهلا
AI: أهلاً بك! يسعدني جداً اهتمامك بتطوير مهاراتك معنا في Kayfa Academy.

لكي أتمكن من ترشيح الكورس الأنسب لك، هل يمكنك إخباري ببعض التفاصيل؟
1. ما هو المجال الذي تهتم به؟ (مثلاً: البرمجة، الأمن السيبراني، تحليل البيانات، أو غيرها؟)
2. ما هو مستواك الحالي في هذا المجال؟ (مبتدئ، متوسط، أم محترف؟)
3. هل تبحث عن كورس قصير لتعلم مهارة محددة، أم تفضل الانضمام لبرنامج تدريبي متكامل (دبلومة) لتغيير مسارك المهني؟

بانتظار ردك لأقدم لك أفضل الاقتراحات!
Human: اسمك ايه
AI: أنا المساعد الذكي الخاص بـ Kayfa Academy، ومهمتي هي مساعدتك في اختيار المسار التعليمي الأنسب لك وتزويدك بكل المعلومات التي تحتاجها عن دوراتنا ودبلوماتنا.

كيف يمكنني مساعدتك اليوم؟ هل لديك مجال معين تود الاستفسار عنه؟



You: انا حابب الذكاء الاصطناعي وتحليل البيانات
انا حابب الذكاء الاصطناعي وتحليل البيانات
اختيار ممتاز! مجالا الذكاء الاصطناعي (AI) وتحليل البيانات (Data Science) هما من أكثر المجالات طلباً ومستقبلاً في سوق العمل حالياً.

في Kayfa Academy، لدينا مسارات قوية جداً في هذه التخصصات. لكي أعطيك تفاصيل دقيقة، هل تفضل أن أبحث لك عن **دورات تدريبية قصيرة** لتبدأ بها وتجرب المجال، أم تود التعرف على **الدبلومات المتكاملة** التي تؤهلك لدخول سوق العمل كمحترف؟

كما يمكنني تزويدك بمعلومات مفصلة عن محتوى دبلومة "Data Science" لدينا إذا كنت مهتماً بمعرفة ما ستتعلمه بالتحديد. ما رأيك؟



You: عايز اشترك في الدبلومة دي
عايز اشترك في الدبلومة دي
خطوة ممتازة! دبلومة علوم البيانات (Data Science) في Kayfa Academy مصممة لتأخذك من الصفر حتى الاحتراف، وتؤهلك للعمل في هذا المجال الحيوي.

سأقوم الآن بالبحث عن كافة التفاصيل المتعلقة بهذه الدبلومة (المحتوى، المدة، والمهارات التي ستكتسبها) لأعرضها عليك بشكل كامل.

بما أنك اتخذت قرارك بالاشتراك، لكي أتمكن من تسجيل بياناتك في نظامنا والتواصل معك لإتمام إجراءات التسجيل، أحتاج منك تزويدي بالمعلومات التالية:
1. **اسمك الكريم.**
2. **رقم هاتفك.**

بمجرد تزويدي بهذه البيانات، سأقوم بحفظها في نظامنا (CRM) وسيتواصل معك فريقنا المختص في أقرب وقت لتزويدك بكافة التفاصيل النهائية وتأكيد اشتراكك.



You: عبدالله فكري ورقمي 01234567891
عبدالله فكري ورقمي 01234567891
New Ticket have been recorded: {'Name': 'عبدالله فكري', 'Phone Number': '01234567891', 'Interest': 'Data Science Diploma', 'Conversational Summary': 'العميل عبدالله فكري مهتم بالاشتراك في دبلومة Data Science. تم أخذ بياناته للتواصل معه.', 'State': 'Hot Lead'}

أهلاً بك يا أستاذ عبدالله، وشكراً لثقتك في Kayfa Academy.

لقد قمت بتسجيل بياناتك بنجاح في نظامنا، وتم حفظ اهتمامك بدبلومة **Data Science**. سيقوم فريقنا المختص بالتواصل معك في أقرب وقت ممكن على رقم هاتفك الذي زودتني به (01234567891) لتزويدك بكافة التفاصيل المتعلقة بمحتوى الدبلومة، المواعيد، والخطوات القادمة للبدء.

هل هناك أي استفسار آخر يمكنني مساعدتك به قبل أن يتواصل معك الفريق؟



You: شكرا ليك
شكرا ليك
عفواً يا أستاذ عبدالله، لا شكر على واجب! يسعدني جداً أنني تمكنت من مساعدتك.

أتمنى لك كل التوفيق في رحلتك التعليمية في مجال علوم البيانات، وأنا واثق أنها ستكون خطوة مميزة في مسارك المهني. إذا احتجت لأي استفسار آخر في المستقبل، فلا تتردد في العودة إليّ.

بالتوفيق!



You: close
close
New Ticket have been recorded: {'Name': 'عبدالله فكري', 'Phone Number': '01234567891', 'Interest': 'Data Science Diploma', 'Conversational Summary': 'العميل عبدالله فكري مهتم بدبلومة Data Science وقام بتزويد بياناته للتواصل معه. تم إنهاء المحادثة بناءً على طلبه.', 'State': 'Hot Lead'}

تم حفظ بياناتك بنجاح، وسيتواصل معك فريقنا قريباً. أتمنى لك يوماً سعيداً، ومع السلامة!

---
---
---